name: build

on:
  push:
    paths-ignore:
      - '*.md'

  workflow_dispatch: 

jobs: 
  build-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Using Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v1
        with:
          java-version: 16

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew build
