name: release

on:
  release:
    types:
      - created

  workflow_dispatch:

jobs:
  release-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Using Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16

      - name: Build with Gradle
        run: ./gradlew.bat packageExe

  release-macos:
    runs-on: macos-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Using Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew packageDmg

  release-linux:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Using Caches
        uses: actions/cache@v2
        with:
          path: ~/.gradle/caches
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: 16

      - name: Grant Execute Permission to gradlew
        run: chmod +x gradlew

      - name: Build with Gradle
        run: ./gradlew packageDeb
